### BASIC GAME CONFIGURATION - (DO NOT CHANGE) ###

DISPLAY_WIDTH = 1920
DISPLAY_HEIGHT = 1080
TILES_RANGE = 11
MAP_SIZE = 99
BASIC_TILE = 32

TILE_SIZE = round(DISPLAY_HEIGHT / TILES_RANGE, 0)
REFRESHING_1 = DISPLAY_WIDTH / 2 - (TILE_SIZE * (TILES_RANGE + 2)) / 2
REFRESHING_2 = (TILES_RANGE + 2) * TILE_SIZE
REFRESHING_3 = DISPLAY_WIDTH / 2 + (TILE_SIZE * (TILES_RANGE + 2)) / 2